# Use root/example as user/password credentials
version: '3.1'

services:
  mongodb:
    image: bitnami/mongodb
    ports: 
      - 27017:27017

  mysqldb:
    image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysqldb
    links:
      - mysqldb:db 
    